# Generated by Django 4.2.7 on 2023-11-20 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0004_issue_developer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="developer",
            new_name="assign_to",
        ),
    ]
